import os
from google import genai
import sys

# Ensure local imports work cleanly
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from src.core.agent import BaseAgent
from src.core.message_bus import Message, AsyncMessageBus

class ReviewerAgent(BaseAgent):
    """
    The Reviewer Agent analyzes code generated by the Worker.
    It acts as a gatekeeper, either approving the code or rejecting it 
    and sending it back to the Worker for revisions.
    """
    def __init__(self, message_bus: AsyncMessageBus):
        super().__init__(name="Reviewer", role="Code Quality Analyst", message_bus=message_bus)
        self.client = genai.Client()
        
    async def process_message(self, message: Message):
        if message.metadata.get("action") != "review_code":
            return
            
        print(f"\n[Reviewer] Analyzing code quality...")
        
        prompt = f"""
        You are a strict, senior Code Reviewer. Review the following Python code.
        If the code is flawless and production-ready, output EXACTLY the word "APPROVED" and nothing else.
        If the code has errors, lacks docstrings, or is inefficient, output the requested changes.
        
        Code to review:
        {message.content}
        """
        
        # Use a "pro" reasoning model for critique and analysis
        response = self.client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt
        )
        
        feedback = response.text.strip()
        
        if "APPROVED" in feedback.upper():
            print("[Reviewer] Code approved. Passing to Orchestrator.")
            # End of the agent loop, send final approved code back to the central Orchestrator
            await self.send(
                content=message.content, 
                receiver_id="Orchestrator",
                metadata={"action": "task_complete"}
            )
        else:
            print("[Reviewer] Code rejected. Sending back to Worker for revision.")
            # Reject and route back to the worker
            await self.send(
                content=f"Fix these issues:\n{feedback}\n\nOriginal Code:\n{message.content}",
                receiver_id="Worker",
                metadata={"action": "revise_code"}
            )
